graph LR
  N001["*HOME / Samsung VXT CMS<br/>https://www.samsungvx.com/"]
  N002[/"vxt.samsung.com"/]
  N003["HOME / Samsung VXT CMS<br/>https://www.samsungvx.com/"]

  N001 -.->|"Click 'Contact Us'"| N002
  N001 -->|"Click 'chatbot' !"| N003

  %% legend: * entry  ! mutating  ? confirmation  ^ upload  x error
  %% dashed edges were recorded but not traversed
